### ISSUE TITLE
Add documentation about setting up nginx

### ISSUE THREAD

**Issue by aelisya** [etesync/server-skeleton#5]
The connexion nginx <-> uwsgi <-> server not very easy
And
pip install -r requirements.txt won't work anymore
pip3 install -r requirements.txt

Please redo your doc with real example thank you in advance

**Comment by tasn** [comment]
I updated the title because it was not very descriptive...
Regarding the pip issue: pip here points to pip3 (because virtulaenv points to virtualenv3). I'm happy to change this in the docs to make it more clear, but this is not an issue, and it's a real example. The real issue here is that you're using an environment that still points to python2 by default a decade after python3 has been released and 3 years after python2's original end-of-life date.

As for nginx: which server (if at all) you're using in front of etesync is out of scope for this documentation. I don't think it's a good idea for us to start documenting every possible variation of tech to be put in front of etesync. Should I also write a guide about setting up postgres?
This is especially true since we are using django, and there are a lot of resources about using django with nginx.
For example, the first result on Google: https://uwsgi-docs.readthedocs.io/en/latest/tutorials/Django_and_nginx.html

I'm closing this ticket, as neither of those is really an issue.

**Comment by Akito13** [comment]
> 
> 
> I updated the title because it was not very descriptive...
> Regarding the pip issue: pip here points to pip3 (because virtulaenv points to virtualenv3). I'm happy to change this in the docs to make it more clear, but this is not an issue, and it's a real example. The real issue here is that you're using an environment that still points to python2 by default a decade after python3 has been released and 3 years after python2's original end-of-life date.
> 
> As for nginx: which server (if at all) you're using in front of etesync is out of scope for this documentation. I don't think it's a good idea for us to start documenting every possible variation of tech to be put in front of etesync. Should I also write a guide about setting up postgres?
> This is especially true since we are using django, and there are a lot of resources about using django with nginx.
> For example, the first result on Google: https://uwsgi-docs.readthedocs.io/en/latest/tutorials/Django_and_nginx.html
> 
> I'm closing this ticket, as neither of these is really an issue.

I strongly disagree. I am sitting since a couple of hours on setting up the server and it just won't work because the documentation is lacking. 

> Using the debug server in production is not recommended, so you should configure your webserver to serve etesync (with TLS). An example on how to do so with nginx can be found here.

This should be documented step by step for the server, as the provided _uwsgi-docs_ is a general description and does not apply 1 to 1 to this server and I can't wrap my head around it. 
The critical step not working in the uwsgi documentation is the following:

> And if that works, run it using uWSGI:
> 
> `uwsgi --http :8000 --module mysite.wsgi`
> 
> * module mysite.wsgi: load the specified wsgi module
> 

There is no module that I could find.

Setting up _nginx_ as proposed with those 2 micro-sentences from the README requires uwsgi to work properly, so linking the uwsgi-docs is not at all sufficient, as it describes a different case (apparently) than it is with this server.

Sure, if someone wants to know how Django works, they should look up Django documentation. If they want to know how uwsgi works, they should look up uwsgi-docs. But here the only part that doesn't work is the part where all the knowledge from Django and uwsgi, in this specific case, does not apply to this specific server.
The documentation is definitely lacking and this is a bad sign. I actually wanted to commit some README improvements due to the lack of installation documentation, after I finish installing but I can't even do this, due to the extreme lack of knowing what the hell the user is supposed to do.

The reason I was about to post an issue, is because I am out of ideas and if it won't be solved with this appeal, then I won't use this server, as it currently doesn't do what it says.

**Comment by tasn** [comment]
Fair enough. I still think setting up nginx is out of scope, but I'm willing to add examples / documentation because I understand it may be a struggle. Though just to reiterate, EteSync-server is as standard and simple as django applications get.

I also want to add a Docker configuration file, which will completely encode how to set it up, and obviously also make it easy to just spin servers up if you're a docker user.

In the meanwhile, please feel free to reach out via IRC/email and I'll personally help you with your setup. Contact info: https://www.etesync.com/about/#contact

**Comment by Akito13** [comment]
@tasn Well, thank you very much. As mentioned, I would be able to provide (i.e. contribute) some more extensive examples/documentation on how to set up this stuff to make it possible for average users to create their own sync economy.

> I also want to add a Docker configuration file, which will completely encode how to set it up, and obviously also make it easy to just spin servers up if you're a docker user.

Definitely a good idea.

**Comment by tasn** [comment]
There's already a community docker image, but I haven't reviewed it myself, so I can't attest to its quality.

**Comment by tasn** [comment]
Is this solved with the example nginx configuration that's in the repo nowadays? (under example-configs)

I'd think so and will close this ticket if there are no objections, please let me know.

**Comment by Akito13** [comment]
> 
> 
> Is this solved with the example nginx configuration that's in the repo nowadays? (under example-configs)
> 
> I'd think so and will close this ticket if there are no objections, please let me know.

Once I get to it, I will do some stuff with this nice project. Currently, not possible, so you may close the ticket. (Is the OP still here?)

**Comment by Schabolon** [comment]
> 
> 
> Is this solved with the example nginx configuration that's in the repo nowadays? (under example-configs)
> 
> I'd think so and will close this ticket if there are no objections, please let me know.

It would be nice if the example-configs folder would be mentioned in the README so it is easier to find.

**Comment by aelisya** [comment]
oh sorry i have totally forgot this thread i will close (you can reopen it if you want)
